- name: AWS ec2 key management
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: crreate a new key pair called test2
    ec2_key:
      aws_access_key: '{{ aws_id }}'
      aws_secret_key: '{{ aws_key }}'
      name: test2
      region: us-east-1
      state: present
