- name: host info for lynx installation-1
  hosts: amazon-linux
  connection: ssh
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
  - name: install the package for lynx browser
    yum: pkg=lynx state=installed update_cache=true
