- name: starting multiple instances
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks: 
  - name: start all the mentioned servers
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      aws_region: "{{ aws_region }}"
      instance_ids: ['i-0967a13b2337d33e3', 'i-07c80e905dff9417e']
      state: running
